ports:
   - port: 8081
     onOpen: open-preview
tasks:
   - before: cp .bashrc ~/.bashrc && pip3 install -r requirements.txt
     command: . .bashrc && echo fAST for Deep Learning ... && cd /workspace/demo && ./run.sh datasets/github_java_10/4/1.java
   - command: . .bashrc && echo fAST for Parsing, Slicing, Diffing ... && cd /workspace/demo/datasets && ./download
